# Generated by Django 4.0.5 on 2022-06-12 11:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(upload_to='')),
                ('name', models.CharField(help_text="Enter a person's name.", max_length=50)),
                ('bio', models.CharField(help_text="Enter a person's bio.", max_length=200)),
                ('status', models.CharField(blank=True, choices=[('exact', 'exact identification'), ('inexact', 'inexact identification')], default='inexact identification', help_text='Measure of identification exactness.', max_length=30)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'permissions': (('moderator_required', 'Set user as moderator'),),
            },
        ),
    ]
