# Generated by Django 4.0.5 on 2022-06-13 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_photo_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='name',
            field=models.CharField(help_text="Enter a person's name.", max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.FileField(help_text="Enter a person's photo", upload_to='static/images'),
        ),
    ]
