# Generated by Django 4.0.5 on 2022-06-17 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_photo_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': (['name'],), 'permissions': (('moderator_required', 'Set user as moderator'),)},
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.FileField(help_text="Enter a person's photo", max_length=50, upload_to='images_base'),
        ),
    ]
